version: "3.8"

services:

  arangodb:
    image: arangodb:latest
    container_name: arangodb
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD}
    networks:
    - backend_net
    volumes:
      - arango_data:/var/lib/arangodb3

  postgres:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
    - backend_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask_api:
    build:
      context: .
    container_name: flask_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
    - backend_net
    depends_on:
      - arangodb
      - postgres

volumes:
  arango_data:
  postgres_data:

networks:
  backend_net:
    name: backend_net  
    driver: bridge
