version: '3.8'

services:
  # Service FastAPI
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"  # Mappe le port local 8000 au port 8000 du conteneur
    depends_on:
      - postgres  # L'application FastAPI dépend du service PostgreSQL
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatabase  # Connexion à PostgreSQL

  # Service PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Mappe le port 5432 local au port 5432 du conteneur PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persister les données de la base de données

  # (Optionnel) Un service pour les migrations si vous utilisez Alembic ou d'autres outils
  migrations:
    build: .
    container_name: fastapi-migrations
    depends_on:
      - postgres
    command: ["alembic", "upgrade", "head"]  # Exemple pour appliquer les migrations
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatabase

volumes:
  postgres_data:
    driver: local
