# Generated by Django 4.2.20 on 2025-03-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Aggregation', '0002_cours_etudiant_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('note_pedagogie', models.FloatField()),
                ('date', models.DateField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Aggregation.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Aggregation.etudiant')),
            ],
        ),
    ]
