# Generated by Django 4.2.20 on 2025-03-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Aggregation', '0003_commentairecours'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_nom', models.CharField(max_length=100)),
                ('satisfaction', models.FloatField()),
                ('nb_participants', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
