name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      arangodb:
        image: arangodb:latest
        env:
          ARANGO_ROOT_PASSWORD: ${{ secrets.ARANGO_PASSWORD }}
        ports:
          - 8529:8529

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test ArangoDB availability
        run: |
          until curl --output /dev/null --silent --head --fail "http://localhost:8529/_admin/server/availability"; do
            printf 'Waiting for ArangoDB to be ready...\n'
            sleep 10
          done

      - name: Run tests
        run: echo "No tests to run"
