name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      arangodb:
        image: arangodb:latest
        env:
          ARANGO_ROOT_PASSWORD: ${{ secrets.ARANGO_PASSWORD }}
        ports:
          - 8529:8529
        options: >-
          --health-cmd="curl --fail --silent http://arangodb:8529/_admin/server/availability || exit 1"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start services
        run: |
          docker pull arangodb:latest
          docker run -d -e ARANGO_ROOT_PASSWORD=${{ secrets.ARANGO_PASSWORD }} -p 8529:8529 --name arangodb arangodb:latest

      - name: Check ArangoDB logs early
        run: |
          sleep 10
          docker logs arangodb

      - name: Wait for services to be ready
        run: sleep 30

      - name: Test ArangoDB availability
        run: curl --fail http://arangodb:8529/_admin/server/availability

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Debug ArangoDB logs if failure
        if: failure()
        run: docker logs arangodb
