name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      arangodb:
        image: arangodb:latest
        env:
          ARANGO_ROOT_PASSWORD: ${{ secrets.ARANGO_PASSWORD }}
        ports:
          - 8529:8529
        options: >-
          --health-cmd="curl --fail --silent http://localhost:8529/_admin/server/availability || exit 1"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=15

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: "5432"
      ARANGO_HOST: http://localhost:8529
      ARANGO_USER: root
      ARANGO_PASSWORD: ${{ secrets.ARANGO_PASSWORD }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TOKEN_URL: ${{ secrets.TOKEN_URL }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for services to be ready
        run: sleep 30

      - name: Test ArangoDB availability
        run: curl --fail http://localhost:8529/_admin/server/availability

      - name: Run tests
        run: pytest tests/

      - name: Debug ArangoDB logs if failure
        if: failure()
        run: docker logs $(docker ps -aqf "ancestor=arangodb:latest")
